name: Sync GitHub Issues to Markdown

on:
  # Run manually
  workflow_dispatch:
    inputs:
      sync_mode:
        description: 'Sync mode'
        required: true
        default: 'missing'
        type: choice
        options:
        - missing
        - all
        - force
  
  # Run on schedule (daily at 2 AM UTC)
  schedule:
    - cron: '0 2 * * *'
  
  # Run when issues are updated (optional)
  issues:
    types: [opened, edited, closed, labeled, assigned]

permissions:
  contents: write     # we write markdown files and images
  issues: read        # we read issue data
  pull-requests: read

jobs:
  sync-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify PROJECTS_TOKEN
        run: |
          if [ -z "${{ secrets.PROJECTS_TOKEN }}" ]; then
            echo "::error::Missing PROJECTS_TOKEN secret"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4   
        with:
          node-version: '18'

      - name: Install deps
        run: npm install gray-matter @actions/github @actions/core

      - name: Sync GitHub Issues to Markdown
        env:
          PROJECTS_TOKEN: ${{ secrets.PROJECTS_TOKEN }}
          OWNER: sctgithub              # org or username that owns the Project v2
          PROJECT_NUMBER: 8             # project number from UI
          STATUS_FIELD_NAME: Status     # single-select field driving board columns
          TASKS_DIR: Tasks
          SYNC_MODE: ${{ github.event.inputs.sync_mode || 'missing' }}
        run: node .github/scripts/sync-github-to-md.js